# Default values for alea.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
Name: alea
region: eu-central-1

## Persistent Storage Configuration
#
#  The chart creates 2 persistent storage types: for standard (slower) disks,
#  and SSD (faster) disks.
#
#   See: https://github.com/kubernetes/kubernetes/blob/release-1.4/examples/experimental/persistent-volume-provisioning/README.md
#
#    - standardClassName: Name for the standard storage class
#    - ssdClassName: Name for the ssd storage class
#    - provisioner: Provisioner to use:
#        - GCE: kubernetes.io/gce-pd
#        - AWS: kubernetes.io/aws-ebs
#    - standardType: Disk type to use for standard storage class
#    - ssdType: Disk type to use for fast storage class
#    - zone: AZ to use for storage
#    - iopsPerGB: iops string value for AWS type storage
#
storage:
  # glacialClassName: slowest
  standardClassName: slow
  ssdClassName: fast
  # iopsClassName: fastest
  provisioner: kubernetes.io/aws-ebs
  # glacialType: sc1    # Cold HDD,                 500GiB - 16TB
  standardType: st1   # Throughput Optimized HDD, 500GiB - 16TB
  ssdType: gp2        # General Purpose SSD,      1GiB - 16TB
  # iopsSsdType: io1    # Provisioned IOPS SSD,     4GiB - 16TB
  zone: eu-central-1
  iopsPerGB: "50"     # for AWS, iopsSSD only

etcd:
  PeerPort: 2380
  ClientPort: 2379
  Component: "etcd"
  Replicas: 3
  Image: "gcr.io/google_containers/etcd-amd64"
  ImageTag: "2.2.5"
  ImagePullPolicy: "Always"
  Cpu: "100m"
  Memory: "512Mi"
  Storage: "1Gi"

mongo:
  diskName: mongodb-data-disk
  storageClassName: fast
  diskSize: 500Gi
  imageTag: 3.2.9-r2
  imagePullPolicy: IfNotPresent
  dbRootPassword: "root"
  dbUsername: "api"
  dbPassword: "mypass"
  dbDatabase: "alea-controller"

postgres:
  imageTag: latest
  imagePullPolicy: IfNotPresent
  diskNamePrefix: pg-data-disk
  storageClassName: fast
  diskSize: 200Gi
  username: stolon
  password: password
  database: backing_services

redis:
  diskName: redis-data-disk
  storageClassName: slow
  diskSize: 500Gi # Minimum value
  imageTag: latest

controller:
  imageTag: v0.1.0 # latest
  imagePullPolicy: "Always" # "IfNotPresent"
  # Create a secret by running:
  # docker run --rm quay.io/codaisseur/alea-controller rails secret
  # then put it in your custom.yaml.
  secretKeyBase: ""
