apiVersion: v1
kind: Secret
metadata:
  name: api
  labels:
    app: api
    heritage: deis-backing-services
type: Opaque
data:
  secretKeyBase: {{ default "" .Values.api.secretKeyBase | b64enc | quote }}
