apiVersion: v1
kind: Service
metadata:
  name: services-api
  labels:
    app: backing-services-api
    heritage: deis-backing-services
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: backing-services-api
