apiVersion: v1
kind: Service
metadata:
  name: memcached-1
  labels:
    heritage: deis-backing-services
spec:
  ports:
  - name: memcached-port-1
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: memcached-1

---

apiVersion: v1
kind: Service
metadata:
  name: memcached-2
  labels:
    heritage: deis-backing-services
spec:
  ports:
  - name: memcached-port-2
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    app: memcached-2

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached-1
  labels:
    app: memcached-1
    heritage: deis-backing-services
spec:
  replicas: 1
  selector:
    name: memcached-1
    mode: cluster
    provider: memcached
  template:
    metadata:
      labels:
        name: memcached-1
        mode: cluster
        provider: memcached
    spec:
      containers:
      - name: memcached
        image: "memcached:1.4.24"
        ports:
        - containerPort: 11211
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: memcached-2
  labels:
    heritage: deis-backing-services
    app: memcached-2
spec:
  replicas: 1
  selector:
    name: memcached-2
    mode: cluster
    provider: memcached
  template:
    metadata:
      labels:
        name: memcached-2
        mode: cluster
        provider: memcached
    spec:
      containers:
      - name: memcached
        image: "memcached:1.4.24"
        ports:
        - containerPort: 11211
