kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.mongo.diskName }}-claim"
  labels:
    heritage: deis-backing-services
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.mongo.storageClassName }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.diskSize }}
