apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
    heritage: deis-backing-services
type: Opaque
data:
  postgres-password: {{ default "" .Values.postgres.password | b64enc | quote }}
