apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alea-controller
  labels:
    heritage: alea
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: alea-controller
  template:
    metadata:
      labels:
        app: alea-controller
    spec:
      containers:
        - name: alea-controller
          image: "quay.io/codaisseur/alea-controller:{{ .Values.controller.imageTag }}"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: "DATABASE_URL"
              value: "postgres://{{ default "postgres" .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres-pooling-service.services:5432/{{ .Values.postgres.database }}"
            - name: "MEMCACHED_SERVERS"
              value: "memcached-1.services,memcached-2.services"
            - name: "MONGODB_URL"
              value: "mongodb://root:{{ .Values.mongo.dbRootPassword }}@mongodb-service.services:27017/admin"
            - name: "PORT"
              value: "5000"
            - name: "RAILS_ENV"
              value: production
            - name: "RACK_ENV"
              value: production
            - name: "REDIS_URL"
              value: "redis://redis-slave.services:26379/redis_services"
            - name: "SECRET_KEY_BASE"
              valueFrom:
                secretKeyRef:
                  name: alea-controller
                  key: secretKeyBase
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 10
