apiVersion: v1
kind: Service
metadata:
  name: alea-controller-service
  labels:
    app: alea-controller
    heritage: alea
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: alea-controller
