apiVersion: v1
kind: Secret
metadata:
  name: alea-controller
  labels:
    app: alea-controller
    heritage: alea
type: Opaque
data:
  secretKeyBase: {{ default "" .Values.controller.secretKeyBase | b64enc | quote }}
