apiVersion: v1
kind: Service
metadata:
  labels:
    etcd_node: etcd0
    heritage: alea
  name: etcd0
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: server
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    etcd_node: etcd0
