apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongo.diskName }}
  labels:
    heritage: alea
    name: {{ .Values.mongo.diskName }}
spec:
  capacity:
    storage: {{ .Values.mongo.diskSize }}
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: {{ .Values.mongo.diskName | quote }}
    fsType: "ext4"
