apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-apps
    heritage: alea
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb-service
