apiVersion: v1
kind: Secret
metadata:
  name: mongodb-apps
  labels:
    app: mongodb-apps
    heritage: alea
type: Opaque
data:
  mongodb-root-password: {{ default "" .Values.mongo.dbRootPassword | b64enc | quote }}
  mongodb-password: {{ default "" .Values.mongo.dbPassword | b64enc | quote }}
