apiVersion: v1
kind: Service
metadata:
  name: postgres-secondary-2-service
  labels:
    name: postgres-secondary-2
    node: secondary-2
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: postgres
    node: secondary-2
