apiVersion: v1
kind: Service
metadata:
  name: postgres-secondary-1-service
  labels:
    name: postgres-secondary-1
    node: secondary-1
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: postgres
    node: secondary-1
