apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-service
  labels:
    name: postgres-primary
    node: primary
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: postgres
    node: primary
