kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.postgres.diskName }}-claim"
  labels:
    heritage: alea
  annotations:
    volume.beta.kubernetes.io/storage-class: "{{ .Values.postgres.storageClassName }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.diskSize }}
