apiVersion: v1
kind: Service
metadata:
  name: postgres-pooling-service
  labels:
    name: postgres-pooling
    node: pgpool
spec:
  ports:
  - name: pgpool
    port: 5432
    targetPort: pgpool
  selector:
    app: postgres
    node: pgpool
