apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.postgres.diskName }}"
  labels:
    heritage: alea
    name: "{{ .Values.postgres.diskName }}"
spec:
  capacity:
    storage: {{ .Values.postgres.diskSize }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "{{ .Values.postgres.diskName }}"
    fsType: "ext4"
