apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-secondary-2
  labels:
    app: postgres
    heritage: alea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        node: secondary-2
        heritage: alea
    spec:
      containers:
      - name: postgres-secondary-2
        image: "paunin/postgresql-cluster-pgsql:{{ default "" .Values.postgres.imageTag }}"
        imagePullPolicy: {{ default "Always" .Values.postgres.imagePullPolicy }}
        env:
        - name: "REPLICATION_PRIMARY_HOST"
          value: "postgres-secondary-1-service"
        - name: "NODE_ID"
          value: "3"
        - name: "NODE_NAME"
          value: "node3"
        - name: "CLUSTER_NODE_NETWORK_NAME"
          value: "postgres-secondary-2-service"
        - name: "REPLICATION_UPSTREAM_NODE_ID"
          value: "2"
        - name: "POSTGRES_PASSWORD"
          value: {{ .Values.postgres.password | quote }}
        ports:
        - name: postgres
          containerPort: 5432
