apiVersion: v1
kind: Service
metadata:
  name: pgset-master
  labels:
    heritage: alea
    name: pgset-master
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 0
  selector:
    name: pgset-master
  sessionAffinity: None
