apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: alea
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
  selector:
    redis-sentinel: "true"
