kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.redis.diskName }}
  labels:
    heritage: alea
    name: {{ .Values.redis.diskName }}
spec:
  capacity:
    storage: {{ .Values.redis.diskSize }}
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: {{ .Values.redis.diskName | quote }}
    fsType: "ext4"
