apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    heritage: alea
spec:
  replicas: 3
  selector:
    name: redis
  template:
    metadata:
      labels:
        app: redis-cluster
        name: redis
    spec:
      containers:
      - name: redis
        image: "deis/redis:v2.2.4"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
