apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-sentinel
  labels:
    heritage: alea
spec:
  replicas: 3
  selector:
    redis-sentinel: "true"
  template:
    metadata:
      labels:
        name: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
        provider: redis
    spec:
      containers:
      - name: sentinel
        image: "deis/redis:v2.2.4"
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
