apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.diskName }}
  labels:
    heritage: alea
    name: {{ .Values.redis.diskName }}
spec:
  capacity:
    storage: {{ .Values.redis.diskSize }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ .Values.redis.diskName | quote }}
    fsType: "ext4"
