apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "redis-master"
  labels:
    heritage: alea
    app: "redis"
    role: "master"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "redis"
        role: "master"
    spec:
      containers:
        - name: "redis-master"
          image: "wallnerryan/redis:{{ default "" .Values.redis.imageTag }}"
          env:
          - name: GET_HOSTS_FROM
            value: env
          command: ["/usr/bin/redis-server", "--appendonly","yes"]
          ports:
            - name: "redis-server"
              containerPort: 6379
          volumeMounts:
            - name: redis-master-data
              mountPath: "/var/lib/redis"
      volumes:
        - name: redis-master-data
          persistentVolumeClaim:
            claimName: "{{ .Values.redis.diskName }}-claim"
