kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ .Values.storage.standardClassName }}
  labels:
    heritage: alea
provisioner: {{ .Values.storage.provisioner }}
parameters:
  type: {{ .Values.storage.standardType }}
  zone: {{ default "" .Values.storage.zone }}
  # iopsPerGB: {{ default "" .Values.storage.iopsPerGB | quote }} only for io1
