apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-sentinel-deployment
  labels:
    heritage: alea
    app: stolon-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: stolon-sentinel
        stolon-cluster: "kube-stolon"
        stolon-sentinel: "true"
        heritage: alea
    spec:
      containers:
      - name: stolon-sentinel
        image: sorintlab/stolon:master-pg9.6
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: SENTINEL
            value: "true"
          - name: STSENTINEL_CLUSTER_NAME
            value: "kube-stolon"
          - name: STSENTINEL_STORE_BACKEND
            value: "etcd" # Or consul
          - name: STSENTINEL_STORE_ENDPOINTS
            value: "http://etcd0.services:2379,http://etcd1.services:2379,http://etcd2.services:2379"
            # Enable debugging
          - name: STSENTINEL_DEBUG
            value: "true"
