apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-proxy-deployment
  labels:
    heritage: alea
    role: stolon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: stolon-proxy
        stolon-cluster: "kube-stolon"
        stolon-proxy: "true"
        heritage: alea
    spec:
      containers:
      - name: stolon-proxy
        image: sorintlab/stolon:master
        env:
          - name: PROXY
            value: "true"
          - name: STPROXY_CLUSTER_NAME
          # TODO(sgotti) Get cluster name from "stoloncluster" label using a downward volume api instead of duplicating the name here
            value: "kube-stolon"
          - name: STPROXY_STORE_BACKEND
            value: "etcd" # Or consul
          - name: STPROXY_STORE_ENDPOINTS
            value: "etcd-service:2379"
            # Enable debugging
          - name: STPROXY_DEBUG
            value: "true"
        ports:
          - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          timeoutSeconds: 5
