apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy-service
  labels:
    heritage: alea
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    stolon-proxy: "true"
    stolon-cluster: "kube-stolon"
