#!/usr/bin/env ruby

require 'yaml'

chart = YAML.load_file(File.expand_path('../alea/Chart.yaml', __FILE__))
index = YAML.load_file(File.expand_path('../index.yaml.tpl', __FILE__))

index["apiVersion"] ||= "v1"
index["entries"] ||= []

release = {
  "description" => chart["description"],
  "created" => File.mtime("alea-#{chart["version"]}.tgz").iso8601(10)
}
