kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-data-1-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-data-2-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
